import tendorflow

In [1]:
pip install tensorflow

verify installation

In [2]:
import tensorflow as tf
print(tf.__version__)

2.19.0


create tensors


In [9]:
a=tf.constant(5)
print(a)

v=tf.constant([1,2,3,])
print(v)

m=tf.constant([[1,2],[3,4]])
print(m)

t3=tf.constant([[[1,2],[3,4]],[[4,5],[6,7]]])
print(t3)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]], shape=(2, 2, 2), dtype=int32)


tensor addition

In [15]:
a=tf.constant([10,20,30])
b=tf.constant([50,60,70])
c=tf.add(a,b)
print(c)

d=tf.subtract(a,b)
print(d)

e=tf.multiply(a,b)
print(e)

f=tf.divide(a,b)
print(f)

g=tf.pow(a,2)
print(g)

tf.Tensor([ 60  80 100], shape=(3,), dtype=int32)
tf.Tensor([-40 -40 -40], shape=(3,), dtype=int32)
tf.Tensor([ 500 1200 2100], shape=(3,), dtype=int32)
tf.Tensor([0.2        0.33333333 0.42857143], shape=(3,), dtype=float64)
tf.Tensor([100 400 900], shape=(3,), dtype=int32)


In [16]:
a=tf.constant([10,20,30])
print(a.dtype, a.shape, tf.rank(a))

<dtype: 'int32'> (3,) tf.Tensor(1, shape=(), dtype=int32)


numpy array to tensors

In [17]:
import numpy as np
np_array = ([[1,2,3],[4,5,6]])

tensor=tf.convert_to_tensor(np_array)
print(tensor)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
